// Generated by gencpp from file service_pkg/DriveReqRes.msg
// DO NOT EDIT!


#ifndef SERVICE_PKG_MESSAGE_DRIVEREQRES_H
#define SERVICE_PKG_MESSAGE_DRIVEREQRES_H

#include <ros/service_traits.h>


#include <service_pkg/DriveReqResRequest.h>
#include <service_pkg/DriveReqResResponse.h>


namespace service_pkg
{

struct DriveReqRes
{

typedef DriveReqResRequest Request;
typedef DriveReqResResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DriveReqRes
} // namespace service_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::service_pkg::DriveReqRes > {
  static const char* value()
  {
    return "ab3dacaa1aef4690d4987eda2d4ff0e2";
  }

  static const char* value(const ::service_pkg::DriveReqRes&) { return value(); }
};

template<>
struct DataType< ::service_pkg::DriveReqRes > {
  static const char* value()
  {
    return "service_pkg/DriveReqRes";
  }

  static const char* value(const ::service_pkg::DriveReqRes&) { return value(); }
};


// service_traits::MD5Sum< ::service_pkg::DriveReqResRequest> should match
// service_traits::MD5Sum< ::service_pkg::DriveReqRes >
template<>
struct MD5Sum< ::service_pkg::DriveReqResRequest>
{
  static const char* value()
  {
    return MD5Sum< ::service_pkg::DriveReqRes >::value();
  }
  static const char* value(const ::service_pkg::DriveReqResRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_pkg::DriveReqResRequest> should match
// service_traits::DataType< ::service_pkg::DriveReqRes >
template<>
struct DataType< ::service_pkg::DriveReqResRequest>
{
  static const char* value()
  {
    return DataType< ::service_pkg::DriveReqRes >::value();
  }
  static const char* value(const ::service_pkg::DriveReqResRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::service_pkg::DriveReqResResponse> should match
// service_traits::MD5Sum< ::service_pkg::DriveReqRes >
template<>
struct MD5Sum< ::service_pkg::DriveReqResResponse>
{
  static const char* value()
  {
    return MD5Sum< ::service_pkg::DriveReqRes >::value();
  }
  static const char* value(const ::service_pkg::DriveReqResResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_pkg::DriveReqResResponse> should match
// service_traits::DataType< ::service_pkg::DriveReqRes >
template<>
struct DataType< ::service_pkg::DriveReqResResponse>
{
  static const char* value()
  {
    return DataType< ::service_pkg::DriveReqRes >::value();
  }
  static const char* value(const ::service_pkg::DriveReqResResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVICE_PKG_MESSAGE_DRIVEREQRES_H
