// Generated by gencpp from file service_pkg/DriveReqResResponse.msg
// DO NOT EDIT!


#ifndef SERVICE_PKG_MESSAGE_DRIVEREQRESRESPONSE_H
#define SERVICE_PKG_MESSAGE_DRIVEREQRESRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace service_pkg
{
template <class ContainerAllocator>
struct DriveReqResResponse_
{
  typedef DriveReqResResponse_<ContainerAllocator> Type;

  DriveReqResResponse_()
    : msg_feedback()  {
    }
  DriveReqResResponse_(const ContainerAllocator& _alloc)
    : msg_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msg_feedback_type;
  _msg_feedback_type msg_feedback;





  typedef boost::shared_ptr< ::service_pkg::DriveReqResResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::service_pkg::DriveReqResResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DriveReqResResponse_

typedef ::service_pkg::DriveReqResResponse_<std::allocator<void> > DriveReqResResponse;

typedef boost::shared_ptr< ::service_pkg::DriveReqResResponse > DriveReqResResponsePtr;
typedef boost::shared_ptr< ::service_pkg::DriveReqResResponse const> DriveReqResResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::service_pkg::DriveReqResResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::service_pkg::DriveReqResResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::service_pkg::DriveReqResResponse_<ContainerAllocator1> & lhs, const ::service_pkg::DriveReqResResponse_<ContainerAllocator2> & rhs)
{
  return lhs.msg_feedback == rhs.msg_feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::service_pkg::DriveReqResResponse_<ContainerAllocator1> & lhs, const ::service_pkg::DriveReqResResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace service_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::service_pkg::DriveReqResResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::service_pkg::DriveReqResResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::service_pkg::DriveReqResResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::service_pkg::DriveReqResResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::service_pkg::DriveReqResResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::service_pkg::DriveReqResResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::service_pkg::DriveReqResResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2897a4bc4d7ca330e430870cfdee7314";
  }

  static const char* value(const ::service_pkg::DriveReqResResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2897a4bc4d7ca330ULL;
  static const uint64_t static_value2 = 0xe430870cfdee7314ULL;
};

template<class ContainerAllocator>
struct DataType< ::service_pkg::DriveReqResResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "service_pkg/DriveReqResResponse";
  }

  static const char* value(const ::service_pkg::DriveReqResResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::service_pkg::DriveReqResResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string msg_feedback\n"
"\n"
;
  }

  static const char* value(const ::service_pkg::DriveReqResResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::service_pkg::DriveReqResResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.msg_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DriveReqResResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::service_pkg::DriveReqResResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::service_pkg::DriveReqResResponse_<ContainerAllocator>& v)
  {
    s << indent << "msg_feedback: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.msg_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVICE_PKG_MESSAGE_DRIVEREQRESRESPONSE_H
