// Generated by gencpp from file service_pkg/DriveReqResRequest.msg
// DO NOT EDIT!


#ifndef SERVICE_PKG_MESSAGE_DRIVEREQRESREQUEST_H
#define SERVICE_PKG_MESSAGE_DRIVEREQRESREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace service_pkg
{
template <class ContainerAllocator>
struct DriveReqResRequest_
{
  typedef DriveReqResRequest_<ContainerAllocator> Type;

  DriveReqResRequest_()
    : lin_vel(0.0)
    , ang_vel(0.0)  {
    }
  DriveReqResRequest_(const ContainerAllocator& _alloc)
    : lin_vel(0.0)
    , ang_vel(0.0)  {
  (void)_alloc;
    }



   typedef double _lin_vel_type;
  _lin_vel_type lin_vel;

   typedef double _ang_vel_type;
  _ang_vel_type ang_vel;





  typedef boost::shared_ptr< ::service_pkg::DriveReqResRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::service_pkg::DriveReqResRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DriveReqResRequest_

typedef ::service_pkg::DriveReqResRequest_<std::allocator<void> > DriveReqResRequest;

typedef boost::shared_ptr< ::service_pkg::DriveReqResRequest > DriveReqResRequestPtr;
typedef boost::shared_ptr< ::service_pkg::DriveReqResRequest const> DriveReqResRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::service_pkg::DriveReqResRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::service_pkg::DriveReqResRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::service_pkg::DriveReqResRequest_<ContainerAllocator1> & lhs, const ::service_pkg::DriveReqResRequest_<ContainerAllocator2> & rhs)
{
  return lhs.lin_vel == rhs.lin_vel &&
    lhs.ang_vel == rhs.ang_vel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::service_pkg::DriveReqResRequest_<ContainerAllocator1> & lhs, const ::service_pkg::DriveReqResRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace service_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::service_pkg::DriveReqResRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::service_pkg::DriveReqResRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::service_pkg::DriveReqResRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::service_pkg::DriveReqResRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::service_pkg::DriveReqResRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::service_pkg::DriveReqResRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::service_pkg::DriveReqResRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dd1e8ef004904e0cf53b02a52a0e1b4e";
  }

  static const char* value(const ::service_pkg::DriveReqResRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdd1e8ef004904e0cULL;
  static const uint64_t static_value2 = 0xf53b02a52a0e1b4eULL;
};

template<class ContainerAllocator>
struct DataType< ::service_pkg::DriveReqResRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "service_pkg/DriveReqResRequest";
  }

  static const char* value(const ::service_pkg::DriveReqResRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::service_pkg::DriveReqResRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 lin_vel\n"
"float64 ang_vel\n"
;
  }

  static const char* value(const ::service_pkg::DriveReqResRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::service_pkg::DriveReqResRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lin_vel);
      stream.next(m.ang_vel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DriveReqResRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::service_pkg::DriveReqResRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::service_pkg::DriveReqResRequest_<ContainerAllocator>& v)
  {
    s << indent << "lin_vel: ";
    Printer<double>::stream(s, indent + "  ", v.lin_vel);
    s << indent << "ang_vel: ";
    Printer<double>::stream(s, indent + "  ", v.ang_vel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVICE_PKG_MESSAGE_DRIVEREQRESREQUEST_H
